apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./svc-bar/eu-prod/
- ./svc-bar/us-prod/
- ./svc-baz/eu-prod/
- ./svc-baz/us-prod/
- ./svc-foo/eu-prod/
- ./svc-foo/us-prod/
