---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kustomize-monorepo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: kustomize-env
  url: https://github.com/shubhindia/kustomize_monorepo

