---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-env-monorepo-eu-prod
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./eu-prod/
  prune: true
  sourceRef:
    kind: GitRepository
    name: kustomize-env-monorepo
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-env-monorepo-us-prod
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./us-prod/
  prune: true
  sourceRef:
    kind: GitRepository
    name: kustomize-env-monorepo
  validation: client