---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-monorepo
  namespace: flux-system
spec:
  interval: 5m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: kustomize-monorepo
  validation: client

